// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

/**
 * Read the first env key present. Supports three naming conventions so the
 * app works whether env is provided by our own .env (VITE_*), Vercel's
 * Supabase integration for Vite/Next.js apps (workhub_* / NEXT_PUBLIC_*),
 * or a mix.
 */
function pickEnv(...keys: string[]): string | undefined {
  const env = import.meta.env as Record<string, string | undefined>;
  for (const k of keys) {
    const v = env[k];
    if (v && v.length > 0) return v;
  }
  return undefined;
}

export const SUPABASE_URL = pickEnv(
  'VITE_SUPABASE_URL',
  'NEXT_PUBLIC_workhub_SUPABASE_URL',
  'workhub_SUPABASE_URL',
  'NEXT_PUBLIC_SUPABASE_URL',
);

export const SUPABASE_PUBLISHABLE_KEY = pickEnv(
  'VITE_SUPABASE_PUBLISHABLE_KEY',
  'NEXT_PUBLIC_workhub_SUPABASE_PUBLISHABLE_KEY',
  'workhub_SUPABASE_PUBLISHABLE_KEY',
  'NEXT_PUBLIC_workhub_SUPABASE_ANON_KEY',
  'workhub_SUPABASE_ANON_KEY',
  'NEXT_PUBLIC_SUPABASE_ANON_KEY',
);

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
  global: {
    fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
  },
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});
