// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function pickEnv(...keys: string[]): string | undefined {
  const env = import.meta.env as Record<string, string | undefined>;
  for (const k of keys) {
    const v = env[k];
    if (v && v.length > 0) return v;
  }
  return undefined;
}

export const SUPABASE_URL = pickEnv(
  'VITE_SUPABASE_URL',
  'NEXT_PUBLIC_workhub_SUPABASE_URL',
  'workhub_SUPABASE_URL',
  'NEXT_PUBLIC_SUPABASE_URL',
);

export const SUPABASE_PUBLISHABLE_KEY = pickEnv(
  'VITE_SUPABASE_PUBLISHABLE_KEY',
  'NEXT_PUBLIC_workhub_SUPABASE_PUBLISHABLE_KEY',
  'workhub_SUPABASE_PUBLISHABLE_KEY',
  'NEXT_PUBLIC_workhub_SUPABASE_ANON_KEY',
  'workhub_SUPABASE_ANON_KEY',
  'NEXT_PUBLIC_SUPABASE_ANON_KEY',
);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});
